### ISSUE TITLE
GitFlow support

### ISSUE THREAD

**Issue by nblackburn** [AAlakkad/git-version-bumper#2]
Add support for detecting tags for repos using git flo, support can usually be detected using the `.git/config` or looking for tags under the `release/` namespace (but only when using the default configuration).

```bash
git config --local -l
```

**Comment by AmmarCodes** [comment]
Good idea! if you can submit a pull request I'd be happy to merge it, or I'll try to update it once I got enough time.

**Comment by nblackburn** [comment]
I hacked out a rough implementation of this last night so will send over a PR once i have tidied it up a bit.

**Comment by nblackburn** [comment]
I have made some general improvements over at #3 that will serve as the base for getting this functionality added.

**Comment by nblackburn** [comment]
First pass is up here: https://github.com/nblackburn/git-version-bumper/tree/feature/gitflo-support
